# Generated by Django 3.2.9 on 2021-12-12 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gr_Number', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, null=True)),
                ('added', models.DateTimeField(max_length=8, null=True)),
                ('to_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentapp.group')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('number_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentapp.group')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentapp.subjects')),
            ],
        ),
    ]
