# Generated by Django 3.2.9 on 2021-12-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_group_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
