# Generated by Django 3.2.9 on 2021-12-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_subjects_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Subject'},
        ),
    ]
