# Generated by Django 3.2.9 on 2021-12-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_auto_20211213_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='gr_Number',
            field=models.IntegerField(null=True),
        ),
    ]
