# Generated by Django 3.2.9 on 2021-12-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0008_student_users_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='users_auth',
        ),
    ]
