# Generated by Django 3.2.9 on 2021-12-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0009_auto_20211214_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='gr_Number',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
