# Generated by Django 3.2.9 on 2021-12-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0010_alter_group_gr_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='gr_Number',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
