# Generated by Django 3.2.9 on 2021-12-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0011_alter_group_gr_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Subject_name',
        ),
    ]
