# Generated by Django 4.0.4 on 2022-04-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0013_questions_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_name',
            name='to_group',
        ),
        migrations.AddField(
            model_name='subject_name',
            name='to_group',
            field=models.ManyToManyField(to='studentapp.group'),
        ),
    ]
